### ISSUE TITLE
Create Carousel

### ISSUE THREAD

**Issue by Ashish-khanagwal** [Ashish-khanagwal/50-projects-50-days#10]
## Create a carousel for the Project section.

You can refer to this carousel example :point_right:  [Carousel](https://codepen.io/ashish-khanagwal/pen/xxzwRWo)

![Screenshot from 2022-11-04 01-59-17](https://user-images.githubusercontent.com/75534912/199827608-63f98d49-d5b9-4c02-a0f2-9ce14f34478a.png)

**You can make the Project section responsive too for making it responsive, create another issue and submit a new PR**

**Comment by Naiyya01** [comment]
you mean, like a slider , where we can add our projects ?

**Comment by Ashish-khanagwal** [comment]
yes exactly, you can refer to that :point_right: [example](https://codepen.io/ashish-khanagwal/pen/xxzwRWo)

**Comment by Naiyya01** [comment]
okay, I am working on this.
