### ISSUE TITLE
 About us Section

### ISSUE THREAD

**Issue by Ashish-khanagwal** [Ashish-khanagwal/50-projects-50-days#11]
## Create a **About** section

1. You can create cards too to display information about contributors refer to their about section for inspiration :point_right: [markitup](https://markitup.in/)

2. Or, can create **About** section like this too :point_down: [Eddie hub](https://www.eddiehub.org/)

![Screenshot from 2022-11-04 02-06-34](https://user-images.githubusercontent.com/75534912/199828939-42bddfb4-b1a0-4334-b3c1-ffbe1d018e98.png)

**Note: Let me know what approach you'll be following 1st or 2nd**

**Comment by Drishti-jain21** [comment]
@Ashish-khanagwal I would like to work on this issue
I will be following the 1st approach

**Comment by Ashish-khanagwal** [comment]
Okay :+1: go ahead, and if you need any kind of help then ping me!

**Comment by kirti281003** [comment]
I would like to work on this section using the 2nd approach

**Comment by Ashish-khanagwal** [comment]
Hey @kirti281003, this issue is already assigned to @Drishti-jain21. so, can't assign it to you until got a confirmation from Drishti
well, you both can collaborate on it and she is preferring 1st approach.

**Comment by Ashish-khanagwal** [comment]
@Drishti-jain21 any updates about the issue?
Let me know if you're working on it

**Comment by Drishti-jain21** [comment]
@Ashish-khanagwal Yes i am working on the issue
Will be done by tomorrow

**Comment by Ashish-khanagwal** [comment]
@Drishti-jain21 any updates on it?

**Comment by Drishti-jain21** [comment]
Yes
This is the area where we can write a bit about the contributors/team
<img width="943" alt="image" src="https://user-images.githubusercontent.com/100796147/200334545-993bf993-a90b-4159-a9dc-15b079916e27.png">

Then below it will be the place where the image of contributors will be shown, I am trying to add the slider feature, it's taking some time. 
Will create a pull request by EOD

**Comment by Drishti-jain21** [comment]
The icon is animated

**Comment by Ashish-khanagwal** [comment]
Okay cool!
try to implement linear gradient for headings and implement it in other sections too.
Like this :point_down: 

CODE :point_down:
```
background: linear-gradient(to right, #9544f4 0%, #db03fc 100%);
-webkit-background-clip: text;
-webkit-text-fill-color: transparent;
```

OUTPUT :point_down:
![Screenshot from 2022-11-07 20-03-40](https://user-images.githubusercontent.com/75534912/200336181-5c940a64-7533-48ae-9338-7a11a9a50e17.png)

**If you have any queries, then let me know**

**Comment by Drishti-jain21** [comment]
Ok, got it!
Will do
