### ISSUE TITLE
Adding Height Converter project

### ISSUE THREAD

**Issue by Drishti-jain21** [Ashish-khanagwal/50-projects-50-days#14]
I would like to add a height converter web project which changes Feet+Inches to Centimeters

**Comment by Ashish-khanagwal** [comment]
you can add that project, don't forget to deploy that project using Netlify or Vercel. 
> * Create a directory named after you and then add the project
> * Deploy it using Vercel or Netlify to add its live link in README.md file

**Comment by Ashish-khanagwal** [comment]
Please add your Dev Info in [CONTRIBUTORS.md](https://github.com/Ashish-khanagwal/Awesome-web-dev/blob/main/CONTRIBUTORS.md) file
