### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by Bharatpahwa** [Ashish-khanagwal/50-projects-50-days#20]
We can add landing pages for any traveling website, E-Commerce Website and othes
I am also including a screenshot for a sample
![Screenshot (55)](https://user-images.githubusercontent.com/102665650/200050671-2d3b82c3-9317-46e5-a55e-3bbfd0bb2966.png)
Please assign this to me

**Comment by Ashish-khanagwal** [comment]
you can add, please follow the instructions listed below

> * create a directory named after you to add your project's code base
> * make sure to add the live link and code base link of the project in README.md file
> * To add the project in the site, use at present card template code.
