### ISSUE TITLE
New Coloured Animated Button 

### ISSUE THREAD

**Issue by Bharatpahwa** [Ashish-khanagwal/50-projects-50-days#21]
Sample Attested Below
<img width="278" alt="image" src="https://user-images.githubusercontent.com/102665650/200052718-fc934053-578b-4d57-aed7-d35c3825ac7d.png">
It's Animated and colour is moving

**Comment by Ashish-khanagwal** [comment]
Just want a simple and sobber look, so no requirement for these animated buttons
