### ISSUE TITLE
Adding a loan calculator project

### ISSUE THREAD

**Issue by Drishti-jain21** [Ashish-khanagwal/50-projects-50-days#23]
I want to add a loan calculator project made using HTML, CSS, JavaScript

**Comment by Ashish-khanagwal** [comment]
Okay sure, you can add.
**One more thing, Try to add your project on the website too same as some of the projects presented there**

Like this :point_down: 

![Screenshot from 2022-11-05 22-57-50](https://user-images.githubusercontent.com/75534912/200133220-2b8c8340-b26a-47b5-99f5-4d7dfb869889.png)
