### ISSUE TITLE
Adding Beginner Friendly Projects

### ISSUE THREAD

**Issue by Bharatpahwa** [Ashish-khanagwal/50-projects-50-days#25]
Such as TIC TAC TOE, GUESS MY NUMBER GAME 

<img width="745" alt="image" src="https://user-images.githubusercontent.com/102665650/200126757-b4c3cc4b-87b3-4067-b302-fc7045f75900.png">

**Comment by Ashish-khanagwal** [comment]
Okay sure, you can add.
**One more thing, Try to add your project on the website too same as some of the projects presented there**

Like this :point_down: 

![Screenshot from 2022-11-05 22-57-50](https://user-images.githubusercontent.com/75534912/200133220-2b8c8340-b26a-47b5-99f5-4d7dfb869889.png)
