### ISSUE TITLE
Adding 2048 game

### ISSUE THREAD

**Issue by Drishti-jain21** [Ashish-khanagwal/50-projects-50-days#39]
I want to add 2048 game, made using CSS, HTML and JavaScript

**Comment by Drishti-jain21** [comment]
Hi
I am facing problems in fetching files due to an image in Bharat's web pages. it has .webp extension
Is it ok, if i replace that file with a .png or .jpg file?

**Comment by Drishti-jain21** [comment]
<img width="524" alt="image" src="https://user-images.githubusercontent.com/100796147/200877570-a3b7dd89-e471-4c84-b7b1-abfc53492677.png">

I am facing this problem. Can you please help me as to how I should proceed with it?

**Comment by Ashish-khanagwal** [comment]
What exactly you're trying to do??

**Comment by Ashish-khanagwal** [comment]
> Hi I am facing problems in fetching files due to an image in Bharat's web pages. it has .webp extension Is it ok, if i replace that file with a .png or .jpg file?

you can do that, but you'll have to make changes in his code base too

**Comment by Drishti-jain21** [comment]
Actually due that particular file, i wasn't able to pull the origin

Neither am i able to delete that file nor do anything because of it

**Comment by Drishti-jain21** [comment]
@Ashish-khanagwal I just saw that image wasn't used anywhere in his code, so, is it ok if i delete it?

**Comment by Ashish-khanagwal** [comment]
okay, you can delete that image
