### ISSUE TITLE
Footer of the Website

### ISSUE THREAD

**Issue by geetika001** [Ashish-khanagwal/50-projects-50-days#9]
Hey @Ashish-khanagwal @DhruviThakkar210 I would like to add footer for the website.Please assign me this issue.

**Comment by Ashish-khanagwal** [comment]
@geetika001 okay then, go ahead :+1: , If you want any kind of help then please let me know. Try to synchronize it's design with the hero section

**Comment by Ashish-khanagwal** [comment]
Hey, please make sure to sync your local repo with the remote repo, because made some changes to it.

**Comment by Ashish-khanagwal** [comment]
Thank you for collaborating with us and for your valuable contribution

**Comment by Ashish-khanagwal** [comment]
@geetika001 don't forget to add your Dev Info in our [CONTRIBUTORS.md](https://github.com/Ashish-khanagwal/Awesome-web-dev/blob/main/CONTRIBUTORS.md) file
